name: myapp
description: "A new Flutter project."

# Mencegah paket dipublikasikan ke pub.dev secara tidak sengaja
publish_to: 'none' # Hapus baris ini jika Anda ingin mempublikasikan ke pub.dev

# Versi dan nomor build aplikasi
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies aplikasi
dependencies:
  flutter:
    sdk: flutter

  # Menambahkan ikon Cupertino untuk iOS
  cupertino_icons: ^1.0.8

# Dependencies untuk pengembangan
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^4.0.0

# Konfigurasi untuk flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"
  remove_alpha_ios: true


# Konfigurasi Flutter
flutter:
  uses-material-design: true

  # Jika Anda ingin menambahkan aset lainnya, aktifkan bagian berikut
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Jika Anda ingin menambahkan font kustom, aktifkan bagian berikut
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
